name: conflictmediamirror
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - geopandas  
  - pip
  - streamlit
  - plotly  
  - scikit-learn  
  - transformers  
  - pytorch  
  - spacy  
  - geonamescache  
  - sqlalchemy  
  - pip:
      - country_converter
      - pycountry
      - sqlalchemy
      - altair
      - streamlit_ace
      - streamlit_tags
      - folium
      - streamlit_folium
      - bertopic
