name: conflictmediamirror
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - geopandas  
  - pip
  - streamlit
  - pip:
      - country_converter
      - pycountry
      - sqlalchemy
      - altair
      - streamlit_ace
      - streamlit_tags
      - folium
      - streamlit_folium
